<?php


	return [

		["value" => "0", "name" =>"Not specified"],
		["value" => "1", "name" =>"Afghan"],
		["value" => "2", "name" =>"Albanian"],
		["value" => "3", "name" =>"Algerian"],
		["value" => "4", "name" =>"American"],
		["value" => "5", "name" =>"Andorran"],
		["value" => "6", "name" =>"Angolan"],
		["value" => "7", "name" =>"Antiguan"],
		["value" => "8", "name" =>"Argentinian"],
		["value" => "9", "name" =>"Armenian"],
		["value" => "10", "name" =>"Aruban"],
		["value" => "11", "name" =>"Australian"],
		["value" => "12", "name" =>"Austrian"],
		["value" => "13", "name" =>"Azerbaijani"],
		["value" => "14", "name" =>"Bahamian"],
		["value" => "15", "name" =>"Bahraini"],
		["value" => "16", "name" =>"Bangladeshi"],
		["value" => "17", "name" =>"Barbadian"],
		["value" => "18", "name" =>"Belarusian"],
		["value" => "19", "name" =>"Belgian"],
		["value" => "20", "name" =>"Belizean"],
		["value" => "21", "name" =>"Beninese"],
		["value" => "22", "name" =>"Bermudian"],
		["value" => "23", "name" =>"Bhutanese"],
		["value" => "24", "name" =>"Bolivian"],
		["value" => "25", "name" =>"Bosnian"],
		["value" => "26", "name" =>"Botswanan"],
		["value" => "27", "name" =>"Brazilian"],
		["value" => "28", "name" =>"British"],
		["value" => "29", "name" =>"Bruneian"],
		["value" => "30", "name" =>"Bulgarian"],
		["value" => "31", "name" =>"Burkinese"],
		["value" => "32", "name" =>"Burmese"],
		["value" => "33", "name" =>"Burundian"],
		["value" => "188", "name" =>"Buryat"],
		["value" => "34", "name" =>"Cambodian"],
		["value" => "35", "name" =>"Cameroonian"],
		["value" => "36", "name" =>"Canadian"],
		["value" => "37", "name" =>"Cape Verdean"],
		["value" => "38", "name" =>"Chadian"],
		["value" => "185", "name" =>"Chechen"],
		["value" => "39", "name" =>"Chilean"],
		["value" => "40", "name" =>"Chinese"],
		["value" => "41", "name" =>"Colombian"],
		["value" => "42", "name" =>"Congolese"],
		["value" => "43", "name" =>"Costa Rican"],
		["value" => "44", "name" =>"Croatian"],
		["value" => "45", "name" =>"Cuban"],
		["value" => "46", "name" =>"Cypriot"],
		["value" => "47", "name" =>"Czech"],
		["value" => "48", "name" =>"Danish"],
		["value" => "49", "name" =>"Djiboutian"],
		["value" => "50", "name" =>"Dominican"],
		["value" => "51", "name" =>"Dutch"],
		["value" => "52", "name" =>"Ecuadorean"],
		["value" => "53", "name" =>"Egyptian"],
		["value" => "54", "name" =>"Emirati"],
		["value" => "187", "name" =>"English"],
		["value" => "55", "name" =>"Eritrean"],
		["value" => "56", "name" =>"Estonian"],
		["value" => "57", "name" =>"Ethiopian"],
		["value" => "58", "name" =>"Fijian"],
		["value" => "59", "name" =>"Finnish"],
		["value" => "60", "name" =>"French"],
		["value" => "61", "name" =>"Gabonese"],
		["value" => "62", "name" =>"Gambian"],
		["value" => "63", "name" =>"Georgian"],
		["value" => "64", "name" =>"German"],
		["value" => "65", "name" =>"Ghanaian"],
		["value" => "66", "name" =>"Greek"],
		["value" => "67", "name" =>"Grenadian"],
		["value" => "68", "name" =>"Guatemalan"],
		["value" => "69", "name" =>"Guinean"],
		["value" => "70", "name" =>"Guyanese"],
		["value" => "71", "name" =>"Haitian"],
		["value" => "72", "name" =>"Honduran"],
		["value" => "73", "name" =>"Hungarian"],
		["value" => "74", "name" =>"Icelandic"],
		["value" => "75", "name" =>"Indian"],
		["value" => "76", "name" =>"Indonesian"],
		["value" => "77", "name" =>"Iranian"],
		["value" => "78", "name" =>"Iraqi"],
		["value" => "79", "name" =>"Irish"],
		["value" => "177", "name" =>"Israeli"],
		["value" => "80", "name" =>"Italian"],
		["value" => "183", "name" =>"Ivorian"],
		["value" => "81", "name" =>"Jamaican"],
		["value" => "82", "name" =>"Japanese"],
		["value" => "83", "name" =>"Jordanian"],
		["value" => "84", "name" =>"Kazakh"],
		["value" => "85", "name" =>"Kenyan"],
		["value" => "192", "name" =>"Kurdish"],
		["value" => "86", "name" =>"Kuwaiti"],
		["value" => "184", "name" =>"Kyrgyz"],
		["value" => "190", "name" =>"Kyrgyzstani"],
		["value" => "87", "name" =>"Laotian"],
		["value" => "88", "name" =>"Latvian"],
		["value" => "89", "name" =>"Lebanese"],
		["value" => "90", "name" =>"Liberian"],
		["value" => "91", "name" =>"Libyan"],
		["value" => "92", "name" =>"Liechtensteiner"],
		["value" => "93", "name" =>"Lithuanian"],
		["value" => "94", "name" =>"Luxembourger"],
		["value" => "95", "name" =>"Macedonian"],
		["value" => "96", "name" =>"Madagascan"],
		["value" => "97", "name" =>"Malawian"],
		["value" => "98", "name" =>"Malaysian"],
		["value" => "99", "name" =>"Maldivian"],
		["value" => "100", "name" =>"Malian"],
		["value" => "101", "name" =>"Maltese"],
		["value" => "102", "name" =>"Mauritanian"],
		["value" => "103", "name" =>"Mauritian"],
		["value" => "104", "name" =>"Mexican"],
		["value" => "105", "name" =>"Moldovan"],
		["value" => "106", "name" =>"Monacan"],
		["value" => "107", "name" =>"Mongolian"],
		["value" => "108", "name" =>"Montenegrin"],
		["value" => "109", "name" =>"Moroccan"],
		["value" => "110", "name" =>"Mozambican"],
		["value" => "179", "name" =>"Myanmar"],
		["value" => "111", "name" =>"Namibian"],
		["value" => "112", "name" =>"Nepalese"],
		["value" => "113", "name" =>"New Zealander"],
		["value" => "114", "name" =>"Nicaraguan"],
		["value" => "115", "name" =>"Nigerian"],
		["value" => "116", "name" =>"Nigerien"],
		["value" => "117", "name" =>"North Korean"],
		["value" => "118", "name" =>"Norwegian"],
		["value" => "119", "name" =>"Omani"],
		["value" => "120", "name" =>"Pakistani"],
		["value" => "182", "name" =>"Palestinian"],
		["value" => "121", "name" =>"Panamanian"],
		["value" => "186", "name" =>"Papua New Guinean"],
		["value" => "122", "name" =>"Paraguayan"],
		["value" => "123", "name" =>"Peruvian"],
		["value" => "124", "name" =>"Philippine"],
		["value" => "125", "name" =>"Polish"],
		["value" => "126", "name" =>"Portuguese"],
		["value" => "191", "name" =>"Puerto Rican"],
		["value" => "127", "name" =>"Qatari"],
		["value" => "128", "name" =>"Romanian"],
		["value" => "129", "name" =>"Russian"],
		["value" => "130", "name" =>"Rwandan"],
		["value" => "189", "name" =>"Saint Lucian"],
		["value" => "131", "name" =>"Salvadorean"],
		["value" => "132", "name" =>"Saudi Arabian"],
		["value" => "133", "name" =>"Scottish"],
		["value" => "134", "name" =>"Senegalese"],
		["value" => "135", "name" =>"Serbian"],
		["value" => "136", "name" =>"Seychellois"],
		["value" => "180", "name" =>"Shan"],
		["value" => "137", "name" =>"Sierra Leonian"],
		["value" => "138", "name" =>"Singaporean"],
		["value" => "139", "name" =>"Slovak"],
		["value" => "140", "name" =>"Slovenian"],
		["value" => "141", "name" =>"Solomon Islander"],
		["value" => "142", "name" =>"Somali"],
		["value" => "143", "name" =>"South African"],
		["value" => "144", "name" =>"South Korean"],
		["value" => "145", "name" =>"Spanish"],
		["value" => "146", "name" =>"Sri Lankan"],
		["value" => "181", "name" =>"St. Vincent and the grenadines"],
		["value" => "147", "name" =>"Sudanese"],
		["value" => "148", "name" =>"Surinamese"],
		["value" => "149", "name" =>"Swazi"],
		["value" => "150", "name" =>"Swedish"],
		["value" => "151", "name" =>"Swiss"],
		["value" => "152", "name" =>"Syrian"],
		["value" => "178", "name" =>"Tai"],
		["value" => "153", "name" =>"Taiwanese"],
		["value" => "154", "name" =>"Tajik"],
		["value" => "155", "name" =>"Tanzanian"],
		["value" => "156", "name" =>"Thai"],
		["value" => "157", "name" =>"Togolese"],
		["value" => "158", "name" =>"Trinidadian"],
		["value" => "159", "name" =>"Tunisian"],
		["value" => "160", "name" =>"Turkish"],
		["value" => "161", "name" =>"Turkmen"],
		["value" => "162", "name" =>"Tuvaluan"],
		["value" => "163", "name" =>"Ugandan"],
		["value" => "164", "name" =>"Ukrainian"],
		["value" => "165", "name" =>"Uruguayan"],
		["value" => "166", "name" =>"Uzbek"],
		["value" => "167", "name" =>"Vanuatuan"],
		["value" => "168", "name" =>"Venezuelan"],
		["value" => "169", "name" =>"Vietnamese"],
		["value" => "170", "name" =>"Welsh"],
		["value" => "171", "name" =>"Western Samoan"],
		["value" => "172", "name" =>"Yemeni"],
		["value" => "173", "name" =>"Yugoslav"],
		["value" => "174", "name" =>"Zairean"],
		["value" => "175", "name" =>"Zambian"],
		["value" => "176", "name" =>"Zimbabwean"] 
	];